backend:
  name: github
  repo: Arthnr/eternalstory
  branch: main
  auth_type: implicit
  site_id: "{{ CMS_ENV.GITHUB_CLIENT_ID }}"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "items"
    label: "Items"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "mobs"
    label: "Mobs"
    folder: "content/mobs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "HP", name: "hp", widget: "number" }
      - { label: "Dégâts", name: "damage", widget: "number" }
      - { label: "Localisation", name: "location", widget: "string" }
      - { label: "Loot", name: "loot", widget: "list" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "guides"
    label: "Guides"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }

  - name: "tp-space"
    label: "TP Space"
    folder: "content/tp-space"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Coordonnées", name: "coords", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }
